{% set name = "python-kaleido" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/plotly/Kaleido/releases/download/v{{ version }}/kaleido-{{ version }}.tar.gz
  sha256: e3c522d665350e05013138d025438b09ae1e9d792d09d7bc6b34bcbaf9b99e3b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - kaleido-core ={{ version }}

test:
  requires:
    - plotly >=4.10,<5.0
  imports:
    - kaleido

about:
  home: https://github.com/plotly/Kaleido
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Fast static image export for web-based visualization libraries'
  description: |
    Python interface to Kaleido, a cross-platform library for generating static images
    (e.g. png, svg, pdf, etc.) for web-based visualization libraries, with a
    particular focus on eliminating external dependencies.
  doc_url: https://plotly.com/python/static-image-export/
  dev_url: https://github.com/plotly/Kaleido

extra:
  recipe-maintainers:
    - jonmmease
